# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170826_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
