# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 09:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='username2',
        ),
    ]
