# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 16:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20170830_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postedby', to=settings.AUTH_USER_MODEL),
        ),
    ]
